# Generated by Django 4.1 on 2024-04-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='projects',
        ),
    ]
