# Generated by Django 4.1 on 2024-04-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_laboratory_employee_project_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='Employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.employee'),
        ),
    ]
