# Generated by Django 4.1 on 2024-04-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_project_projects_project_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='Employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='Laboratory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.laboratory'),
        ),
    ]
