# Generated by Django 4.1 on 2024-04-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_laboratory_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='Employee',
        ),
    ]
