# Generated by Django 4.1 on 2024-04-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_laboratory_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='Projects',
            field=models.ManyToManyField(blank=True, to='application.project'),
        ),
    ]
