# Generated by Django 4.1 on 2024-06-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_remove_employee_email_remove_employee_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='patients',
            field=models.ManyToManyField(blank=True, to='application.patient'),
        ),
    ]
